Open feign implementation
kleyton-ohare/car-migo pull request #17
Opened 2022-06-15 08:35 UTC by kleyton-ohare

This is to contemplate the Unosquare Action Item to add a Feign Client functionality.

2022-06-16 13:13 UTC, chrissimpson-unosquare reviewed
All looks good Kleyton!

The only comment I had was on the big method that you could consider breaking down.

2022-06-16 13:13 UTC, chrissimpson-unosquare commented on server/src/main/java/com/unosquare/carmigo/service/JourneyService.java
> +  private GrabDistanceDTO convertDistanceHolderToDistanceViewModel(final DistanceHolder distanceHolder) {
Hi Kleyton!

Do you think you could possibly reduce the size of this method?

I always try and follow the rule of 7.  7 lines per method, 7 methods per class, 7 classes per package.  But that's just me :)

2022-06-17 13:53 UTC, linda-mccall requested changes
left a small suggestion, let me know if you have any questions

2022-07-18 12:25 UTC, linda-mccall approved these changes
looks good 👍

2022-07-18 14:10 UTC, merged